CC=g++
CFLAGS=-std=c++14
INCLUDECADMIUM=-I ../../cadmium/include


all: CommandGenerator.out DevicePhone.out readTextOnDigitalDevice.out iestream.out filterPersonDeviceTypeTo.out filterPersonDeviceTypeMyId.out filterPersonDeviceTypeFrom.out filterPeopleInLocation.out filterNetworksState.out filterNetworks.out filterDevicesState.out filterDevicesNetwork.out filterDevicesMicroKeyboard.out filterCommandGenerator.out doActionTask.out devicesSwitch.out callByPhoneTask.out callByMultiplePhoneTask.out answerRadioTask.out answerPhoneTask.out answerPersonTask.out PeopleInLocation.out NetText.out NetState.out NetRadio.out NetPhone.out DevicesState.out DeviceTextOutbox.out DeviceTextInbox.out DeviceTextClasNewRead.out DeviceTextClasNewBroken.out DeviceRadio.out DevicePhoneMultiple.out readTextOnPaperDevice.out sendCommandByRadio.out sendCommandInPerson.out sendTextTask.out sinkDevices.out sinkReceivingBehavior.out sinkSendingBehavior.out switchFace2Face.out 
switchFace2Face.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/switchFace2Face.o
	$(CC) -o switchFace2Face.out tests_mains/switchFace2Face.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/switchFace2Face.o: tests_mains/switchFace2Face.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/switchFace2Face.cpp -o tests_mains/switchFace2Face.o 

sinkSendingBehavior.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/sinkSendingBehavior.o
	$(CC) -o sinkSendingBehavior.out tests_mains/sinkSendingBehavior.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/sinkSendingBehavior.o: tests_mains/sinkSendingBehavior.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/sinkSendingBehavior.cpp -o tests_mains/sinkSendingBehavior.o 

sinkReceivingBehavior.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/sinkReceivingBehavior.o
	$(CC) -o sinkReceivingBehavior.out tests_mains/sinkReceivingBehavior.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/sinkReceivingBehavior.o: tests_mains/sinkReceivingBehavior.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/sinkReceivingBehavior.cpp -o tests_mains/sinkReceivingBehavior.o 

sinkDevices.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/sinkDevices.o
	$(CC) -o sinkDevices.out tests_mains/sinkDevices.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/sinkDevices.o: tests_mains/sinkDevices.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/sinkDevices.cpp -o tests_mains/sinkDevices.o 

sendTextTask.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/sendTextTask.o
	$(CC) -o sendTextTask.out tests_mains/sendTextTask.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/sendTextTask.o: tests_mains/sendTextTask.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/sendTextTask.cpp -o tests_mains/sendTextTask.o 

sendCommandInPerson.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/sendCommandInPerson.o
	$(CC) -o sendCommandInPerson.out tests_mains/sendCommandInPerson.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/sendCommandInPerson.o: tests_mains/sendCommandInPerson.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/sendCommandInPerson.cpp -o tests_mains/sendCommandInPerson.o 

sendCommandByRadio.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/sendCommandByRadio.o
	$(CC) -o sendCommandByRadio.out tests_mains/sendCommandByRadio.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/sendCommandByRadio.o: tests_mains/sendCommandByRadio.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/sendCommandByRadio.cpp -o tests_mains/sendCommandByRadio.o 

readTextOnPaperDevice.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/readTextOnPaperDevice.o
	$(CC) -o readTextOnPaperDevice.out tests_mains/readTextOnPaperDevice.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/readTextOnPaperDevice.o: tests_mains/readTextOnPaperDevice.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/readTextOnPaperDevice.cpp -o tests_mains/readTextOnPaperDevice.o 

readTextOnDigitalDevice.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/readTextOnDigitalDevice.o
	$(CC) -o readTextOnDigitalDevice.out tests_mains/readTextOnDigitalDevice.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/readTextOnDigitalDevice.o: tests_mains/readTextOnDigitalDevice.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/readTextOnDigitalDevice.cpp -o tests_mains/readTextOnDigitalDevice.o 

iestream.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/iestream.o
	$(CC) -o iestream.out tests_mains/iestream.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/iestream.o: tests_mains/iestream.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/iestream.cpp -o tests_mains/iestream.o 

filterPersonDeviceTypeTo.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterPersonDeviceTypeTo.o
	$(CC) -o filterPersonDeviceTypeTo.out tests_mains/filterPersonDeviceTypeTo.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterPersonDeviceTypeTo.o: tests_mains/filterPersonDeviceTypeTo.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterPersonDeviceTypeTo.cpp -o tests_mains/filterPersonDeviceTypeTo.o 

filterPersonDeviceTypeMyId.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterPersonDeviceTypeMyId.o
	$(CC) -o filterPersonDeviceTypeMyId.out tests_mains/filterPersonDeviceTypeMyId.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterPersonDeviceTypeMyId.o: tests_mains/filterPersonDeviceTypeMyId.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterPersonDeviceTypeMyId.cpp -o tests_mains/filterPersonDeviceTypeMyId.o 

filterPersonDeviceTypeFrom.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterPersonDeviceTypeFrom.o
	$(CC) -o filterPersonDeviceTypeFrom.out tests_mains/filterPersonDeviceTypeFrom.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterPersonDeviceTypeFrom.o: tests_mains/filterPersonDeviceTypeFrom.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterPersonDeviceTypeFrom.cpp -o tests_mains/filterPersonDeviceTypeFrom.o 

filterPeopleInLocation.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterPeopleInLocation.o
	$(CC) -o filterPeopleInLocation.out tests_mains/filterPeopleInLocation.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterPeopleInLocation.o: tests_mains/filterPeopleInLocation.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterPeopleInLocation.cpp -o tests_mains/filterPeopleInLocation.o 

filterNetworksState.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterNetworksState.o
	$(CC) -o filterNetworksState.out tests_mains/filterNetworksState.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterNetworksState.o: tests_mains/filterNetworksState.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterNetworksState.cpp -o tests_mains/filterNetworksState.o 

filterNetworks.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterNetworks.o
	$(CC) -o filterNetworks.out tests_mains/filterNetworks.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterNetworks.o: tests_mains/filterNetworks.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterNetworks.cpp -o tests_mains/filterNetworks.o 

filterDevicesState.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterDevicesState.o
	$(CC) -o filterDevicesState.out tests_mains/filterDevicesState.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterDevicesState.o: tests_mains/filterDevicesState.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterDevicesState.cpp -o tests_mains/filterDevicesState.o 

filterDevicesNetwork.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterDevicesNetwork.o
	$(CC) -o filterDevicesNetwork.out tests_mains/filterDevicesNetwork.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterDevicesNetwork.o: tests_mains/filterDevicesNetwork.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterDevicesNetwork.cpp -o tests_mains/filterDevicesNetwork.o 

filterDevicesMicroKeyboard.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterDevicesMicroKeyboard.o
	$(CC) -o filterDevicesMicroKeyboard.out tests_mains/filterDevicesMicroKeyboard.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterDevicesMicroKeyboard.o: tests_mains/filterDevicesMicroKeyboard.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterDevicesMicroKeyboard.cpp -o tests_mains/filterDevicesMicroKeyboard.o 

filterCommandGenerator.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/filterCommandGenerator.o
	$(CC) -o filterCommandGenerator.out tests_mains/filterCommandGenerator.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/filterCommandGenerator.o: tests_mains/filterCommandGenerator.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/filterCommandGenerator.cpp -o tests_mains/filterCommandGenerator.o 

doActionTask.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/doActionTask.o
	$(CC) -o doActionTask.out tests_mains/doActionTask.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/doActionTask.o: tests_mains/doActionTask.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/doActionTask.cpp -o tests_mains/doActionTask.o 

devicesSwitch.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/devicesSwitch.o
	$(CC) -o devicesSwitch.out tests_mains/devicesSwitch.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/devicesSwitch.o: tests_mains/devicesSwitch.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/devicesSwitch.cpp -o tests_mains/devicesSwitch.o 

callByPhoneTask.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/callByPhoneTask.o
	$(CC) -o callByPhoneTask.out tests_mains/callByPhoneTask.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/callByPhoneTask.o: tests_mains/callByPhoneTask.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/callByPhoneTask.cpp -o tests_mains/callByPhoneTask.o 

callByMultiplePhoneTask.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/callByMultiplePhoneTask.o
	$(CC) -o callByMultiplePhoneTask.out tests_mains/callByMultiplePhoneTask.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/callByMultiplePhoneTask.o: tests_mains/callByMultiplePhoneTask.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/callByMultiplePhoneTask.cpp -o tests_mains/callByMultiplePhoneTask.o 

answerRadioTask.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/answerRadioTask.o
	$(CC) -o answerRadioTask.out tests_mains/answerRadioTask.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/answerRadioTask.o: tests_mains/answerRadioTask.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/answerRadioTask.cpp -o tests_mains/answerRadioTask.o 

answerPhoneTask.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/answerPhoneTask.o
	$(CC) -o answerPhoneTask.out tests_mains/answerPhoneTask.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/answerPhoneTask.o: tests_mains/answerPhoneTask.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/answerPhoneTask.cpp -o tests_mains/answerPhoneTask.o 

answerPersonTask.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/answerPersonTask.o
	$(CC) -o answerPersonTask.out tests_mains/answerPersonTask.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/answerPersonTask.o: tests_mains/answerPersonTask.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/answerPersonTask.cpp -o tests_mains/answerPersonTask.o 

PeopleInLocation.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/PeopleInLocation.o
	$(CC) -o PeopleInLocation.out tests_mains/PeopleInLocation.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/PeopleInLocation.o: tests_mains/PeopleInLocation.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/PeopleInLocation.cpp -o tests_mains/PeopleInLocation.o 

NetText.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/NetText.o
	$(CC) -o NetText.out tests_mains/NetText.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/NetText.o: tests_mains/NetText.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/NetText.cpp -o tests_mains/NetText.o 

NetState.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/NetState.o
	$(CC) -o NetState.out tests_mains/NetState.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/NetState.o: tests_mains/NetState.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/NetState.cpp -o tests_mains/NetState.o 

NetRadio.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/NetRadio.o
	$(CC) -o NetRadio.out tests_mains/NetRadio.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/NetRadio.o: tests_mains/NetRadio.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/NetRadio.cpp -o tests_mains/NetRadio.o 

NetPhone.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/NetPhone.o
	$(CC) -o NetPhone.out tests_mains/NetPhone.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/NetPhone.o: tests_mains/NetPhone.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/NetPhone.cpp -o tests_mains/NetPhone.o 

DevicesState.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/DevicesState.o
	$(CC) -o DevicesState.out tests_mains/DevicesState.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/DevicesState.o: tests_mains/DevicesState.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/DevicesState.cpp -o tests_mains/DevicesState.o

DeviceTextOutbox.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/DeviceTextOutbox.o
	$(CC) -o DeviceTextOutbox.out tests_mains/DeviceTextOutbox.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o  

tests_mains/DeviceTextOutbox.o: tests_mains/DeviceTextOutbox.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/DeviceTextOutbox.cpp -o tests_mains/DeviceTextOutbox.o 

DeviceTextInbox.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/DeviceTextInbox.o
	$(CC) -o DeviceTextInbox.out tests_mains/DeviceTextInbox.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/DeviceTextInbox.o: tests_mains/DeviceTextInbox.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/DeviceTextInbox.cpp -o tests_mains/DeviceTextInbox.o 

DeviceTextClasNewRead.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/DeviceTextClasNewRead.o
	$(CC) -o DeviceTextClasNewRead.out tests_mains/DeviceTextClasNewRead.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/DeviceTextClasNewRead.o: tests_mains/DeviceTextClasNewRead.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/DeviceTextClasNewRead.cpp -o tests_mains/DeviceTextClasNewRead.o 

DeviceTextClasNewBroken.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/DeviceTextClasNewBroken.o
	$(CC) -o DeviceTextClasNewBroken.out tests_mains/DeviceTextClasNewBroken.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/DeviceTextClasNewBroken.o: tests_mains/DeviceTextClasNewBroken.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/DeviceTextClasNewBroken.cpp -o tests_mains/DeviceTextClasNewBroken.o 

DeviceRadio.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/DeviceRadio.o
	$(CC) -o DeviceRadio.out tests_mains/DeviceRadio.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/DeviceRadio.o: tests_mains/DeviceRadio.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/DeviceRadio.cpp -o tests_mains/DeviceRadio.o 

DevicePhoneMultiple.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/DevicePhoneMultiple.o
	$(CC) -o DevicePhoneMultiple.out tests_mains/DevicePhoneMultiple.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o 

tests_mains/DevicePhoneMultiple.o: tests_mains/DevicePhoneMultiple.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/DevicePhoneMultiple.cpp -o tests_mains/DevicePhoneMultiple.o 

DevicePhone.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/DevicePhone.o
	$(CC) -o DevicePhone.out tests_mains/DevicePhone.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o

tests_mains/DevicePhone.o: tests_mains/DevicePhone.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/DevicePhone.cpp -o tests_mains/DevicePhone.o 

CommandGenerator.out: ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o tests_mains/CommandGenerator.o
	$(CC) -o CommandGenerator.out tests_mains/CommandGenerator.o ../../data_structures/communication.o ../../data_structures/nep_model_enum_types.o ../../data_structures/struct_types.o

tests_mains/CommandGenerator.o: tests_mains/CommandGenerator.cpp
	$(CC) -c $(CFLAGS) $(INCLUDECADMIUM) tests_mains/CommandGenerator.cpp -o tests_mains/CommandGenerator.o 

../../data_structures/communication.o: 
	$(CC) -c $(CFLAGS) ../../data_structures/communication.cpp -o ../../data_structures/communication.o 

../../data_structures/nep_model_enum_types.o: 
	$(CC) -c $(CFLAGS) ../../data_structures/nep_model_enum_types.cpp -o ../../data_structures/nep_model_enum_types.o

../../data_structures/struct_types.o: 
	$(CC) -c $(CFLAGS) ../../data_structures/struct_types.cpp -o ../../data_structures/struct_types.o

clean:
	rm -f *.out *.o *~; done
	-for d in tests_mains; do (cd $$d; rm -f *.o *~ ); done
	-for d in ../../data_structures; do (cd $$d; rm -f *.o *~ ); done


