#!/bin/bash
./CommandGenerator.out
./DevicePhone.out
./DevicePhoneMultiple.out
./DeviceRadio.out
./DeviceTextClasNewBroken.out
./DeviceTextClasNewRead.out
./DeviceTextInbox.out
./DeviceTextOutbox.out
./DevicesState.out
./NetPhone.out
./NetRadio.out
./NetState.out
./NetText.out
./PeopleInLocation.out
./answerPersonTask.out
./answerPhoneTask.out
./answerRadioTask.out
./callByMultiplePhoneTask.out
./callByPhoneTask.out
./devicesSwitch.out
./doActionTask.out
./filterCommandGenerator.out
./filterDevicesMicroKeyboard.out
./filterDevicesNetwork.out
./filterDevicesState.out
./filterNetworks.out
./filterNetworksState.out
./filterPeopleInLocation.out
./filterPersonDeviceTypeFrom.out
./filterPersonDeviceTypeMyId.out
./filterPersonDeviceTypeTo.out
./iestream.out
./readTextOnDigitalDevice.out
./readTextOnPaperDevice.out
./sendCommandByRadio.out
./sendCommandInPerson.out
./sendTextTask.out
./sinkDevices.out
./sinkReceivingBehavior.out
./sinkSendingBehavior.out
./switchFace2Face.out